import { SiTelegram, SiWhatsapp, SiYoutube } from "react-icons/si";

export const SUPPORT_CHANNELS = [
  {
    name: "Join our WhatsApp Channel",
    description: "Announcements and updates",
    href: "https://whatsapp.com/channel/0029Vb6sMEy96H4VI2w3I50F",
    icon: SiWhatsapp,
    color: "#25D366",
    group: "community",
  },
  {
    name: "Join our WhatsApp Backup Channel",
    description: "A second place for announcements and updates.",
    href: "https://whatsapp.com/channel/0029Vb78BHmL2AU7fsANSH2y",
    icon: SiWhatsapp,
    color: "#25D366",
    group: "community",
  },
  {
    name: "Join our WhatsApp Group",
    description: "Ask questions and chat with other users.",
    href: "https://chat.whatsapp.com/If0d4XKHITO2NUf6YvQ3Eg?s=cl&p=a&mlu=4&ilr=4",
    icon: SiWhatsapp,
    color: "#25D366",
    group: "community",
  },
  {
    name: "Join our Telegram Group",
    description: "Community discussion and general support.",
    href: "https://t.me/CODEXV3",
    icon: SiTelegram,
    color: "#26A5E4",
    group: "community",
  },
  {
    name: "Join our Telegram Channel",
    description: "Announcements and project updates.",
    href: "https://t.me/codex_tech_innovation",
    icon: SiTelegram,
    color: "#26A5E4",
    group: "community",
  },
  {
    name: "Join our YouTube Channel ",
    description: "Tutorials, demos, and walkthroughs.",
    href: "https://www.youtube.com/@CODEXSPACEX",
    icon: SiYoutube,
    color: "#FF0000",
    group: "learning",
  },
  {
  name: "Reach out to us",
  description: "Developer contact",
  href: "https://t.me/codexverified",
  icon: SiTelegram,
  color: "#26A5E4",
  group: "community",
},
];
